//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpdeskBusinessDataObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HelpDeskDBEntities : DbContext
    {
        public HelpDeskDBEntities()
            : base("name=HelpDeskDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Department> Departments { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Problem> Problems { get; set; }
    
        public virtual int GetDepartmentInfoAndSurnameForEmployee(Nullable<int> empID, ObjectParameter deptID, ObjectParameter deptName, ObjectParameter employeeSurname)
        {
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("empID", empID) :
                new ObjectParameter("empID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDepartmentInfoAndSurnameForEmployee", empIDParameter, deptID, deptName, employeeSurname);
        }
    
        public virtual int GetDepartmentInfoForEmployee(Nullable<int> empID, ObjectParameter deptID, ObjectParameter deptName)
        {
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("empID", empID) :
                new ObjectParameter("empID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDepartmentInfoForEmployee", empIDParameter, deptID, deptName);
        }
    
        public virtual ObjectResult<string> GetEmployeeFullNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetEmployeeFullNames");
        }
    
        public virtual ObjectResult<string> GetEmployeeFullNamesInDept(Nullable<int> dept)
        {
            var deptParameter = dept.HasValue ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetEmployeeFullNamesInDept", deptParameter);
        }
    
        public virtual ObjectResult<string> pGetEmployeeFullNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pGetEmployeeFullNames");
        }
    
        public virtual ObjectResult<string> pGetEmployeeFullNamesInDept(Nullable<int> dept)
        {
            var deptParameter = dept.HasValue ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pGetEmployeeFullNamesInDept", deptParameter);
        }
    }
}
