//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpdeskBusinessDataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public int ProblemID { get; set; }
        public string Description { get; set; }
    }
}
